### ISSUE TITLE
MidiJackGetSendEndpointName() not working in standalone builds

### ISSUE THREAD

**Issue by r4dian** [Nagitch/MidiJack#6]
Testing on Windows 10, Unity 2017.4.27f1 and 2018.4.0f1

Using the `ExampleSend.unity` scene, no devices appear in the dropdown.

When adding `Debug.Log(string.Format("MIDI Device ID: {0:X}, Name: {1}", id, name));` statements to see the device info, the Names are always `unknown`

**Comment by Nagitch** [comment]
hi, my environment Win10 2018.3.11f1 is running fine.
MIDI IN and OUT devices are both unknown?
(please see `Window>MIDI Jack`  window)

harhaps this PR may help you.
https://github.com/keijiro/MidiJack/pull/38

**Comment by r4dian** [comment]
In `Window>MIDI Jack` they are named correctly.
After doing `File>Build & Run` they are unknown  in the build.

I will try the PR you linked, thank you.

**Comment by Nagitch** [comment]
sorry for misreading. i got same issue in standalone build.
i'll investigate it.
2019.1.0f2 is same.

**Comment by Nagitch** [comment]
@r4dian I fixed this issue and merged to master. please try it if you would like.

**Comment by r4dian** [comment]
Great that fixed it.
(The `.unitypackage` is out of date, but copying the lose Assets\MidiJack\Plugins into my project fixed it. )

Thank you!
